### ISSUE TITLE
Test suite failure of install_default@uefi

### ISSUE THREAD

**Issue by tcooper** [rocky-linux/os-autoinst-distri-rocky#10]
## Describe Issue

In testing system (qemu worker running in a VirtualBox VM on macOS host, ie. virt-in-virt) all `uefi` machine target build fail during initial boot and never enter installer.

| Test Suite | install_default@uefi, install_blivet_lvm_ext4@uefi, install_blivet_standard_partition_ext4@uefi, install_lvm_ext4@uefi |
|---|---|
| Result | **failed** |
| Scheduled product | `rocky-8.4-dvd-iso-x86_64` |
| Test module | `/var/lib/openqa/share/tests/rocky/tests/_boot_to_anaconda.pm` |
| Analysis | *Test died: no candidate needle with tag(s) `anaconda_select_install_lang` matched*<br>Video indicates node displays intaller menu but doesn't get grub params, likely issue with uefi machine configuration |

## Planned Action
- Verify issue in alternate testing configuration such as qemu on physical hardware to ensure it's not isolated to this test environment.
- If boot issue is resolved complete test development on that hardware.
- If boot issue is not resolved escalate to releng.
- Alternate (possible) solution is to use UEFI on openQA guest that is running virt-in-virt.

**NOTE: UEFI based installs in VirtualBox on macOS have been manually verified to work.**

**Comment by akatch** [comment]
I was able to get past this failure running OpenQA on physical hardware and am continuing to work through the UEFI machine tests.

**Comment by akatch** [comment]
Having fixed the blivet stuff, there are no more UEFI-specific failures in the `dvd-iso` flavor. There are still the following UEFI failures in the `universal` flavor:

```
# install_simple_freespace@uefi
[2021-10-26T15:43:25.0723 CDT] [error] HDD_1 handling Cannot find HDD_1 asset hdd/disk_freespace_gpt.img!

# install_delete_partial@uefi
[2021-10-26T15:43:05.0728 CDT] [error] HDD_1 handling Cannot find HDD_1 asset hdd/disk_full_gpt.img!

# install_multi@uefi
[2021-10-26T15:13:25.0668 CDT] [error] HDD_2 handling Cannot find HDD_2 asset hdd/disk_full_mbr.img!

# install_delete_pata@uefi
[2021-10-26T15:13:45.0642 CDT] [error] HDD_1 handling Cannot find HDD_1 asset hdd/disk_full_mbr.img!
```

I suspect these failures all have the same or very similar root causes. Propose closing this issue, and I would be glad to create new issues for these specific failures.

**Comment by tcooper** [comment]
@akatch seems fine to me. One more upvote from @lumarel and/or @StackKorora gets the issue closed. 👍🏻

**Comment by lumarel** [comment]
I also think that this can be closed, beside the uefi install with the `boot-iso` flavor everything works now 👌🏻 ✔

**Comment by tcooper** [comment]
Two 👍🏻 == closing
