### ISSUE TITLE
[BUG] Language-specific test suites fail on software_selection

### ISSUE THREAD

**Issue by akatch** [rocky-linux/os-autoinst-distri-rocky#101]
**Describe the bug**
The following test suites all fail on `_software_selection` module with `Test died: no candidate needle with tag(s) 'anaconda_minimal_highlighted' matched`:
```
install_arabic_language
install_asian_language
install_cyrillic_language
install_european_language
```

The failed step shows that the Virtualization Host package set is selected rather than the Minimal package set. Example from `install_arabic_language` below.

**To Reproduce**
```
# openqa-cli api -X POST isos ISO=Rocky-8.6-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=8.6 BUILD=8.6_universal_20220607.222847.0 PACKAGE_SET=minimal IDENTIFICATION=false TEST=install_arabic_language,install_asian_language,install_cyrillic_language,install_european_language
```

**Expected behavior**
The Minimal package set should be selected and the tests should pass.

**Screenshots**
![](https://i.ibb.co/3CtxJ8Z/canvas.png)

**Comment by lumarel** [comment]
That was fixed in the middle of some of the previous PRs 👌🏻
