### ISSUE TITLE
[FEATURE] Add dnf contentdir override support

### ISSUE THREAD

**Issue by tcooper** [rocky-linux/os-autoinst-distri-rocky#118]
**Is your feature request related to a problem? Please describe.**
When testing a new release access to staging repositories is possible during initial install but not in post-install or in chained tests using saved machine images.

**Describe the solution you'd like**
RelEng publishes repositories to a custom directory in the primary download server. openQA has hooks to allow the installation repositories to point at these repos. After install is complete the local repository definitions will point at production repository directories which may/may not exist.

Provide mechanism to allow toggle to staging repositories in `dnf` configuration. Solution must work for all supported releases with staging repositories.

**Describe alternatives you've considered**
openQA has hooks that allow build/test from Fedora koji and/or pungi composes. Since Rocky 9 builds in Peridot don't use koji/pungi an alternate solution is needed.
Rocky 8, still built in koji, will be migrated to Peridot as well so solution using existing hooks for Fedora koji/pungi are not ideal as effort spent there would become deprecated after the move.
A common solution using `dnf` configuration in `/etc/dnf/vars/contentdir` seems most appropriate.

**Comment by lumarel** [comment]
I think this has already been resolved with the PR 🙂
