### ISSUE TITLE
Test suite failure for server_cockpit_updates@64bit on rocky-8.4-dvd-iso-x86_64

### ISSUE THREAD

**Issue by tcooper** [rocky-linux/os-autoinst-distri-rocky#14]
## Describe Issue

Significant updates exist between current Rocky DVD ISO and Rocky public repositories causing update to take quite a while in virt-in-virt environment. It's possible simply faster test system will make parts of the test go away. However, during the test it appears that portions of `cockpit` are also updated and the service is restarted. This causes the `cockpit` web UI to be disconnected. It's unclear at this point if that issue is related or not.

| Test Suite | server_cockpit_updates@64bit |
|---|---|
| Result | **failed** ( 31:26 minutes ) |
| Scheduled product | `rocky-8.4-dvd-iso-x86_64` |
| Test module | `/var/lib/openqa/share/tests/rocky/tests/server_cockpit_updates.pm` |
| Analysis | *Test died: no candidate needle with tag(s) `cockpit_updates_updated` matched*<br>Guest disables display (from cockpit) during updates. Needle match impossible. |

## Planned Action
- Run through this sequence in a standard VM (or with test paused) to determine what the nominal sequence should be and rewrite test appropriately.

## Special Notes
- Test can run from `disk_64bit_cockpit.qcow2` image if it is saved and stored appropriately in the test system. There is no need to run from beginning and/or trigger from `install_default_upload@64bit`.

**Comment by lumarel** [comment]
As far as I can see this test ran through on my bigger node, so I suppose this fails really because of the performance limitation. It took about 9min for me.
Disconnects are not visible in the Test-log but this could simply be a miss or match if the moment where cockpit is not available is caught.
