### ISSUE TITLE
Test suite failure for install_default@uefi on rocky-8.4-dvd-iso-x86_64

### ISSUE THREAD

**Issue by akatch** [rocky-linux/os-autoinst-distri-rocky#16]
## Describe Issue
Test Suite | install_default@uefi 
-|-
Result  | **failed** ( 04:46 minutes )
Scheduled product |`rocky-8.4-dvd-iso-x86_64`
Test module | `/var/lib/openqa/share/tests/rocky/tests/_software_selection.pm `

## Analysis 
```
Test died: command 'egrep '(selected env|Selecting the.*environment)' /tmp/anaconda.log /tmp/packaging.log | tail -1 | grep custom-environment' failed at /var/lib/openqa/share/tests/rocky/tests/_software_selection.pm line 28.
```
This string indeed does not appear in the anaconda log. The comments around this line reference components that don't appear anywhere in this logfile:
```
# pre-F35 line looks like:
# 07:51:39,382 INF modules.payloads.payload.dnf.utils: selected environment: custom-environment          
# F35+ line looks like:
# 07:40:26,614 DBG ui.lib.software: Selecting the 'custom-environment' environment.
```

## Planned Action
* The tests are looking for a package group that exists in Fedora but not Rocky.
* Update the test to find a line in the logs referencing the correct package group.

**Comment by tcooper** [comment]
@akatch I think the key here may be that the meaning of `default` in the Fedora tests is to select the `default` software selection for that ISO and it likely is a different package set than is the case for Rocky even where we might imagine it should be the same.

Fedora has Workstation and Server ISOs that have predefined `default` packages while Rocky uses the DVD ISO to support all software selections, a Minimal ISO to provide a smaller ISO for download that has only a limited possible software selection and the Boot ISO which requires a network connection and off-host repository.

I've been using `PACKAGE_SET={minimal|server}` to lock into a specific software selection in my tests to remove some of the variation and control the flow through the test suites along a path I'm familiar with.

If we can verify the `default` Software Selection for all Rocky ISOs we can implement the required behavior for each ISO when no `PACKAGE_SET` is specified. This is tangentially related to solving the `modularity_test` issue as I believe that default enabled/installed modular packages are likely different with different software selections.

It seems reasonable to create a manual task for somebody without an openQA dev environment to complete `default` installs for each of our ISOs to verify both the default software selection for that ISO and the modules enabled and modular packages installed in the machine after it has been rebooted. I'll create an issue in this repository for that task.

**Comment by tcooper** [comment]
@akatch I was working on this a bit in my local system trying to get `install_default` working with the three ISOs for Rocky 8.5. We should look at merging our progress together into one PR. There is a small issue with `boot-iso` still and also with the `default` behavior in the DVD where the install would normally be `graphical-server-environment` but we haven't specified `DESKTOP=gnome` to trigger the `graphical_wait_login` instead of `console_wait_login`. If we truly want `install_default` to install the _default_ environment we'll need to fix that as well.
