### ISSUE TITLE
Collect software selection, module information and default packages for Rocky ISOs

### ISSUE THREAD

**Issue by tcooper** [rocky-linux/os-autoinst-distri-rocky#18]
We have a need in the openQA automated tests to know what is included in the `default` Software Selection for each Rocky ISO (boot, minimal, dvd) in each supported Rocky architecture (currently, x86_64, aarch64).

This information will inform those working on the openQA automated tests and can be collected without access to an openQA development environment. All that is needed is a physical (or virtual) environment capable of booting the above ISOs and some time to collect the information.

## What to collect...

- When running the Anaconda GUI installer and entering the Software Selection spoke record the name of the automatically selected package group in the left hand UI panel as shown below (the radio button with black dot is selected)...

<img width="806" alt="rocky-dvd-software-selection-default" src="https://user-images.githubusercontent.com/542846/130309430-290c61d6-7485-43c5-83e1-a51eb2ccb6dc.png">

Do not change anything in the Software Selection spoke, just press the `[Done]` button, complete the installation of the machine and reboot.

- After reboot login and collect information about the `enabled`, `disabled` and `installed` modules and installed packages with the following commands...

    - `dnf module list --enabled | grep -Ev "^Rocky|^Last|^Hint|^$"`
    - `dnf module list --disabled | grep -Ev "^Rocky|^Last|^Hint|^$"`
    - `dnf module list --installed | grep -Ev "^Rocky|^Last|^Hint|^$"`
    - `rpm -qa | sort`

Save the output in appropriately labelled output files, upload to Rocky [pastebin](https://rpa.st/) or Github Gist with appropriate expiry and drop the link in a comment on this issue.

## Complete the above for the following ISOs...

- Rocky-8.4-x86_64-boot.iso
- Rocky-8.4-x86_64-minimal.iso
- Rocky-8.4-x86_64-dvd1.iso
- Rocky-8.4-aarch64-boot.iso
- Rocky-8.4-aarch64-minimal.iso
- Rocky-8.4-aarch64-dvd1.iso

If you are able to work on this task please comment in this issue and indicate which ISOs you will take care of.

**Comment by tcooper** [comment]
My idea of using Rocky pastebin (http://rpa.st) to upload the results isn't very good for hundreds of output files so I put everything into a folder / branch of my fork. The summary page is available [here](https://github.com/tcooper/os-autoinst-distri-rocky/blob/issue_18/issue_18/RESULTS.md).

Comments on creating a PR to bring this information directly here or maybe into another location in the rocky-linux Github org would be welcome. I don't really want to pollute this repo with this testing data but also don't want to have it orphaned somewhere else.

Finally, since I don't have an `aarch64` system I'll need somebody else to try to follow my lead to collect for that.

I'll leave this issue open until we've decided on a PR or not for this data.

**Comment by c1728p9** [comment]
@tcooper for aarch64 do you want any reports from any additional configurations? In https://github.com/tcooper/os-autoinst-distri-rocky/pull/4 I only recorded info for the default package set for each ISO.

**Comment by tcooper** [comment]
@c1728p9 Ultimately I think we'll need to verify the values for the entire matrix of `PACKAGE_SET` and `ARCH`. As @akatch has mentioned, we can stub out the verification for `PACKAGE_SET` however verification of the enabled modules for each will need to be done. We can start with `dvd-iso` to cover the most numbers. Since all but `minimal` must be installed in network mode from the `boot-iso` I expect those to match the `dvd-iso` values.

**Comment by tcooper** [comment]
@akatch I've merged Russ's contributions for aarch64 into the branch (named `issue_18`) in my fork of this repo. I would be awesome if you could have a look and help me decide if bringing that content over here would be helpful for your work on `issue_16`.

**Comment by akatch** [comment]
> @akatch I've merged Russ's contributions for aarch64 into the branch (named `issue_18`) in my fork of this repo. I would be awesome if you could have a look and help me decide if bringing that content over here would be helpful for your work on `issue_16`.

Absolutely, it would be helpful to have it all in one place. I imagine eventually we'll want the ARM data in there as well?

**Comment by tcooper** [comment]
@akatch Looking at the files list I'm not sure I want to add everything from that repo into our openQA repository. It think a better location will be the Wiki and/or possible an alternate location like people.rockylinux.org as a reference if we don't want to create a separate repository here in Github.

To help you find the directory in my fork I'm dropping a link here...

https://github.com/tcooper/os-autoinst-distri-rocky/tree/issue_18/issue_18
