### ISSUE TITLE
[BUG] [9.2] [x86_64] Arabic and Russian installers stall on weak password

### ISSUE THREAD

**Issue by akatch** [rocky-linux/os-autoinst-distri-rocky#184]
**Describe the bug**
Upon supplying a weak password at the user creation spoke, Anaconda prompts the user to click "Done" twice to accept the password.

This issue impacts the following test suites:
`install_arabic_language`
`install_cyrillic_language`

**To Reproduce**
1. POST the following jobs to openQA: `openqa-cli api -X POST isos ISO=Rocky-9.2-x86_64-dvd.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSIO
N=9.2 BUILD=-$(date +%Y%m%d)-main-9.2 TEST=install_arabic_language,install_cyrillic_language`
1. All tests will stall at `_do_install_and_reboot` on the user creation spoke. An error is displayed on the bottom of the screen in the appropriate language.

**Expected behavior**
Anaconda should only warn about the weak password and not require a second click. If this is desired behavior, we need to modify our tests to handle a second click where necessary.

**Screenshots**
The failing tests may be seen here:
https://openqa.rockylinux.org/tests/33324#step/_do_install_and_reboot/21
https://openqa.rockylinux.org/tests/33321#step/_do_install_and_reboot/21

Translations of the error:
![An error message is displayed in black Arabic text on a yellow-gold background. To the right is the English translation, reading "Press Done again to use the password anyway."](https://i.ibb.co/v1p3nvg/error-arabic-translated.png)
![An error message is displayed in black Cyrillic text on a yellow-gold background. To the right is the English translation, reading "4. Click Done again to still use the password."](https://i.ibb.co/phvYRyp/error-russian-translated.png)

**Additional context**
This issue *is* reproducible locally. It is unclear why this happens only in the Arabic and Russian installers and not in the Japanese, French, or English language installers. Additionally, I was not able to make this work even with a randomly generated 32-character password including upper and lowercase letters, numbers, and multiple symbols.

**Comment by tcooper** [comment]
@akatch I believe you posted in the 9.3-Release channel that you had a fix for this issue. Please update this issue with any information if it differs from the above.

**Comment by tcooper** [comment]
Resolved with #196
