### ISSUE TITLE
Test suite failure for install_simple_encrypted on rocky-8.4-universal-x86_64

### ISSUE THREAD

**Issue by lumarel** [rocky-linux/os-autoinst-distri-rocky#23]
## Describe Issue

Test Suite | install_simple_encrypted@uefi
-- | --
Result | failed ( 05:18 minutes )
Scheduled product | `rocky-8.4-universal-x86_64`
Test module | `/var/lib/openqa/share/tests/rocky/tests/disk_guided_encrypted.pm`
Analysis | Test died: no candidate needle with tag(s) `anaconda_main_hub_install_destination` matched. at `/var/lib/openqa/share/tests/rocky/tests/disk_guided_encrypted.pm` line 11.

## Planned Action
- Update needle to match Rocky Linux Anaconda interface

**Comment by tcooper** [comment]
@lumarel I'm leaving this one un-labeled on purpose. If I get the permission changes I asked for we can test you ability to manage labels with this one.

**Comment by lumarel** [comment]
@tcooper, @brianclemens Permissions work, thank you!
