### ISSUE TITLE
Create Test suites for often used languages on rocky-8.4-universal-x86_64

### ISSUE THREAD

**Issue by lumarel** [rocky-linux/os-autoinst-distri-rocky#37]
## Describe Issue

As discussed earlier in one of the Testing Team meetings, we would like to have more of the mostly used languages as a test suite.

## Planned Action
- Find out the mostly used languages (or if you have personal interest to have a test suite for a language bring it up)
- Write/adapt the test suite (up to now there are 4 languages available beside the main english tests)

## Special Notes
- This issue can be used as tracking issue for the languages

**Comment by tcooper** [comment]
@lumarel This `[FEATURE]` request is now over 2 years old. Do you still think it's necessary to keep this as an active issue for openQA?

**Comment by lumarel** [comment]
I think we found another way to cope with this 👍🏻
