### ISSUE TITLE
Create Test suite install_german_language on rocky-8.4-universal-x86_64

### ISSUE THREAD

**Issue by lumarel** [rocky-linux/os-autoinst-distri-rocky#38]
## Describe Issue

As mentioned in #37 I would like to add German to the list of the languages which will get a test suite.
It will take some time, but I will create the test suite myself 👌🏻

## Planned Action
- Creation of a test suite for the language German

**Comment by tcooper** [comment]
Nice... is it possible that you added language stuff back into one of your branches?

I fetched a branch from your repo into my openQA box to test something else, re-ran `fifloader.py` and found test-suites for language stuff (Arabic, European, etc) in my configuration that I thought I had removed in an early commit to our `develop` branch.

At first I thought the `git checkout develop...` command in the install script changed behavior after we made `develop` the default branch (still possible) but I'm a little perplexed...

Do you see language based test suites in your system now?

**Comment by lumarel** [comment]
@tcooper The language stuff is only in the rocky-8.4-universal-x86_64 product, you might not be possible to remove it there 🤔
(`openqa-cli api -X POST isos ISO=Rocky-8.4-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=8.4`)

I'm definitely running on the latest version of the develop branch as far as I know (and I also didn't make any changes to the fif files up to now)

So yes I'm having the language tests the whole time :)

**Comment by tcooper** [comment]
@lumarel This `[FEATURE]` request is now over 2 years old. I'm not sure if you were ever able to complete this task. If so, can you provide a PR? If not, do you still think it is important enough to keep as an open issue?

**Comment by lumarel** [comment]
Yep this was something from all back on the beginning we thought might be a good idea, but there is not really a need as we know now 👍🏻
