### ISSUE TITLE
[BUG] - 8.5 has some texts changed

### ISSUE THREAD

**Issue by lumarel** [rocky-linux/os-autoinst-distri-rocky#62]
**Describe the bug**
Some identification needles and translations got changed in 8.5, so we will need to create new needles for these.

**To Reproduce**
Run all test products and find that some tests fail because the needles don't match anymore.

**Expected behavior**
Needles matching

**Screenshots**
![image](https://user-images.githubusercontent.com/42647570/141644235-eb4291c2-e6bf-4953-acaf-78d20bbeeea3.png)

We can use this a general issue for all changes needed for 8.5 if somebody else finds something.

**Comment by tcooper** [comment]
Closed with #64
