### ISSUE TITLE
[FEATURE] Create usecases overview

### ISSUE THREAD

**Issue by lumarel** [rocky-linux/os-autoinst-distri-rocky#72]
## Description

We would like to create a general overview file in which all the usecases of the OpenQA testing are clearly presented.
The best would be to come up with a spreadsheet in markdown, which shows all the testcases, their current status, some details, and other information that might be needed.

## Extra information

We have already gathered some information in the issue https://github.com/rocky-linux/testing/issues/56
So it might be the best to start from there and then further evolve.

**Comment by tcooper** [comment]
@lumarel This [FEATURE] request is now over 2 years old and TBH I don't even remember clearly what the purpose of it is. Reviewing #56 I can see that the vast majority of items are covered in openQA. Is this issue even appropriate to have anymore?

**Comment by lumarel** [comment]
Hmm tbh I think we covered this with https://wiki.rockylinux.org/team/testing/qa_test_cases/ 🙂

**Comment by tcooper** [comment]
Agreed
