### ISSUE TITLE
[FEATURE] Add inter-server tests (aka `support_server` tests)

### ISSUE THREAD

**Issue by lumarel** [rocky-linux/os-autoinst-distri-rocky#73]
**Is your feature request related to a problem? Please describe.**
This feature was already available but was pulled out for the time being, because the base images were missing up to now.
Basically this will allow testing of pxe boot, domain join, and so on.

**Describe the solution you'd like**
Add configuration of support_server and all other parallel running jobs back into the template.

**Additional context**
The configuration is still in the `templates-fedora.fif.json` and `templates-updates-fedora.fif.json` files just needs to be ported over.

**Comment by tcooper** [comment]
@lumarel FYI... I'm working on the `_support_server` test as well as a means to test my `tap` multi-worker setup. I'm trying to get `install_pxeboot` working to verify the networking piece. There is a bit of overlap with what you've done and I'll provide any changes on top of or after your PR is merged. You might want to explicitly skip `install_pxeboot` tests unless you've already done them.
