### ISSUE TITLE
[BUG] openQA guests receive hostname of openQA host system

### ISSUE THREAD

**Issue by akatch** [rocky-linux/os-autoinst-distri-rocky#78]
openQA guests receive the hostname of the openQA host system, causing certain needles to not match. The needles expect the guest to have the hostname `localhost`.

**To Reproduce**
Execute the following tests:
```
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.5 BUILD=dvd-iso_workstation_$(date +%Y%m%d.%H%M%S).0 TEST=install_package_set_workstation
```

The `_console_login` test will fail and the needle captures will show the hostname of the openQA host system rather than `localhost`

**Expected behavior**
openQA guest SUTs should always receive the hostname `localhost`.

**Screenshots**
![@tcooper's environment](https://user-images.githubusercontent.com/542846/157708896-fefa6f3d-fcc9-48a6-a89d-42b8308c0884.png)
![@akatch's environment](https://i.ibb.co/ZJ35Lbr/rocky-root-logged-in-biosfont-20220306.png)

**Desktop**
- Fedora 35

Reported in #77

**Comment by tcooper** [comment]
@akatch it's unclear to me if this is happening anymore in DEV boxes. I'm pretty sure it isn't happening in the production system. Can you update on status and/or close?

**Comment by tcooper** [comment]
Closing for non-recurring issue. Create new issue if it recurs in future.
