### ISSUE TITLE
[8.6 Release Issues] Disk Cleanup Spoke missing

### ISSUE THREAD

**Issue by lumarel** [rocky-linux/os-autoinst-distri-rocky#79]
**Describe the bug**
There is this screen popping up in disk_guided_empty and anaconda_help:
![image](https://user-images.githubusercontent.com/42647570/168184783-15edf792-76fa-4bc7-98de-d5e9c9fc38cb.png)

we need to take care of that (if it comes up run through the process of reclaim and apply)

**To Reproduce**
Run one test suites
- graphical server
- minimal (dvd-iso)
- server
- workstation
- universals 

**Expected behavior**
spoke is taken care off

**Comment by akatch** [comment]
We agreed that increasing the default HDDSIZEGB was the right way to solve this. I can take on fixing this one.

**Comment by lumarel** [comment]
@akatch This is about the "disk is empty but needs to be cleaned to be used" issue
so here we need to take care of that screen, so it is expected and clicked through 👍🏻
This behavior is already present in some test cases, but only if the disk was already used

**Comment by akatch** [comment]
Aha, got it. I can still take this one on unless someone else is dying to do so.
