### ISSUE TITLE
[8.6 Release Issue] Disk sizes are too small for some more tests

### ISSUE THREAD

**Issue by lumarel** [rocky-linux/os-autoinst-distri-rocky#83]
**Describe the bug**
Since the new version, there are a few more tests which break because the disk is too small:
![image](https://user-images.githubusercontent.com/42647570/168186947-1ce725d0-05f0-46c7-ae23-ff31003a8186.png)

I would propose to increase the default with 1 or 2GiB, as there are several tests with 600MiB missing and some with a little over 1GiB

**To Reproduce**
Run test suites like:
- universal
- graphical server
- workstation

especially this one here breaks: rocky-8.6-dvd-iso-x86_64-Build-graphical-server-20220512.184550.0-install_custom_gui_lvm_ext4@uefi

**Expected behavior**
Tests can finish with enough space

**Additional context**
@akatch I heard you are searching for this one 👀

**Comment by akatch** [comment]
I swear I can read. I got this one as well.

**Comment by akatch** [comment]
Fixed in the 8.6 release merge.
